#!/bin/bash
[ "$1" != "confirm" ] && echo This will completely destroy the ../html directory - use "'$0 confirm'" to confirm. && exit
set -e
[ -d ../html ] && rm -r ../html
cp -r html ..
git tag -f fake_head `git rev-list --max-parents=0 HEAD` # Requires recent-ish git; otherwise use git rev-list --parents HEAD|tail -1
pike -DFAKE build
git tag -d fake_head
echo Rebuild complete.
